# Discovery Server Access
eureka:
  instance:
    hostname: product-services
  client:
    serviceUrl:
      defaultZone: http://discovery-microservice:8001/eureka/
    registryFetchIntervalSeconds: 1

# HTTP (Tomcat) server port
server:
  port: 9007

#Connect to MongoServer
spring:
  kafka:
    bootstrap-server: kafka:9092
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: products
      collections: products
  cloud:
    stream:
      default-binder: kafka
      kafka:
          binder:
            autoCreateTopics: true
            brokers:
                - ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      bindings:
        input:
          binder: kafka
          destination: ${TOPIC_NAME:product-topic}
          content-type: application/json
          group: product-input-group
        output:
          binder: kafka
          destination: ${TOPIC_NAME:product-topic}
          group: product-output-group
          content-type: application/json