# Discovery Server Access
eureka:
  instance:
    hostname: product-services
  client:
    serviceUrl:
      defaultZone: http://discovery-microservice:8001/eureka/
    registryFetchIntervalSeconds: 1

# HTTP (Tomcat) server port
server:
  port: 9007

#Connect to MongoServer
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: products
      collections: products
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        input:
          binder: kafka
          destination: cart-topics
          content-type: application/json
          group: input-group-1
        output:
          binder: kafka
          destination: product-topics
          group: product-output-group
          content-type: application/json