server:
  port: ${HOST_PORT:8082}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ecommerce?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          headers: messageType
          autoCreateTopics: true
          broker:
            - ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      bindings:
        input:
          binder: kafka
          destination: ${TOPIC_NAME:product-topics}
          content-type: application/json
          group: order-group